### ISSUE TITLE
why you only released the caffe code ? Not the code of this paper ? 

### ISSUE THREAD

**Issue by wangxiao5791509** [danxuhk/CMT-CNN#1]
Hi, I see your paper in the CVPR 2017, it is a very interesting idea to use thermal image to help rgb image detection. However, I don't understand why you only released the caffe code ? Not the code of this paper ? Looking forward to your replay. Thanks.

**Comment by shridharkini6** [comment]
@danxuhk where is the actual code which we can test

**Comment by gangsterless** [comment]
oh my god,

**Comment by liujianghao1023** [comment]
这个 代码 我......

**Comment by liujianghao1023** [comment]
这个代码咋搞  好乱

**Comment by liujianghao1023** [comment]
这个代码 作者可不可以给下原来的
