### ISSUE TITLE
your Google Drive  is not work, can not open 

### ISSUE THREAD

**Issue by junxuezheng** [danxuhk/CMT-CNN#2]
your Google Drive  is not work,
your "Please first download and install this modified caffe version for CMT-CNN, and test by downloading the trained model and network definition file from Google Drive."can not open  "Google Drive"

**Comment by L-CY** [comment]
I can not open it too.
Could you update the link plz?

**Comment by JosephKJ** [comment]
Please update the link.

**Comment by gangsterless** [comment]
oh , cannot open the link
